# Atari TOS

TARGET = _TOS
TARGETEXTENSION = .ttp

CC = vc +tos
CCOUT = -o=
COPTS = -c -merge-strings -O1 -DATARI $(OUTFMTS)

LD = $(CC)
LDOUT = $(CCOUT)
LDFLAGS = -lm

RM = rm -f

include make.rules
