  "instruction not supported on selected architecture",ERROR,
  "trailing garbage in operand",WARNING,
  "selector prefix ignored",WARNING,
  "data size %d not supported",ERROR,
  "relocation does not allow hi/lo modifier",ERROR,
  "operand doesn't fit into %d bits",WARNING,                         /* 05 */
  "branch destination out of range",ERROR,
  "illegal bit number",ERROR,
  "identifier expected",ERROR,
  "bad operand",ERROR,
  "zero/direct-page addressing not available",ERROR,                  /* 10 */
  "operand not in zero/direct-page range",ERROR,
  "absolute-long addressing not available",ERROR,
  "cpu must be defined before any code is generated",ERROR,
  "unknown cpu model: %s",ERROR,
