  "data size of %d bits is not supported",ERROR,
  "value does not fit into immediate. Allowed range is [-32768:32767]. Value is %i", WARNING,
  "destination address (immediate value) is to far away. Allowed distance/immediate value is [-32768:32767]. Actual distance/immediate value is %i", ERROR,
  "congratulations. Your jump distance (%i) actually goes beyond the scope of [-33,554,432:33,554,431]. We, the creators of Hans, are so proud of you for writing 33 million instructions. You should maybe take a break :D", ERROR,
  "immediate is %i but allowed range is %s for %s", ERROR,